# Generated by Django 5.2 on 2025-04-18 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ниманование типа задачи')),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('assignment_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата поручения')),
                ('execution_date', models.DateField(db_index=True, verbose_name='Дата исполнения')),
                ('execution_status', models.CharField(choices=[('completed', 'completed'), ('on_execution', 'on_execution')], default='on_execution', verbose_name='Статус исполнения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_from', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.group', verbose_name='Тип поручения')),
                ('responsible_executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['assignment_date'],
                'constraints': [models.UniqueConstraint(fields=('title', 'assignment_date'), name='unique_task')],
            },
        ),
    ]
