# Generated by Django 5.2 on 2025-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ниманование типа задачи')),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('assignment_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата поручения')),
                ('execution_date', models.DateField(db_index=True, verbose_name='Дата исполнения')),
                ('execution_status', models.CharField(choices=[('completed', 'исполнено'), ('on_execution', 'на исполнении')], default='on_execution', verbose_name='Статус исполнения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['assignment_date'],
            },
        ),
    ]
