# Generated by Django 5.2 on 2025-12-02 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование типа поручения')),
            ],
            options={
                'verbose_name': 'Тип поручения',
                'verbose_name_plural': 'Типы поручений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('number', models.CharField(blank=True, max_length=56, null=True, verbose_name='Номер поручения')),
                ('resolution', models.TextField(max_length=10000, verbose_name='Резолюция')),
                ('assignment_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата поручения')),
                ('execution_date', models.DateField(db_index=True, verbose_name='Дата исполнения')),
                ('is_closed', models.BooleanField(db_index=True, default=False, verbose_name='Отметка об исполнении поручения инициатором')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Отметка об исполнении поручения исполнителем')),
                ('tasks_application', models.FileField(blank=True, help_text='Разрешенные расширения: doc, docx, pdf, jpg, jpeg, png.', null=True, upload_to='uploaded/tasks_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Приложение к поручению')),
                ('executions_application', models.FileField(blank=True, help_text='Разрешенные расширения: doc, docx, pdf, jpg, jpeg, png.', null=True, upload_to='uploaded/applications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Приложение к исполнению')),
                ('executions_comment', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Комментарий к исполнению')),
                ('executors', models.ManyToManyField(related_name='execution_tasks', to='departments.employee', verbose_name='Исполнители')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.group', verbose_name='Тип поручения')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_tasks', to='departments.employee', verbose_name='Инициатор')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redirected_tasks', to='tasks.task', verbose_name='Родительское поручение')),
            ],
            options={
                'verbose_name': 'Поручение',
                'verbose_name_plural': 'Поручения',
                'ordering': ['execution_date'],
                'constraints': [models.UniqueConstraint(fields=('title', 'number', 'initiator', 'assignment_date'), name='unique_task')],
            },
        ),
    ]
