# Generated by Django 5.2 on 2025-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execution_status',
            field=models.CharField(choices=[('исполнено', 'исполнено'), ('на исполнении', 'на исполнении')], default='на исполнении', verbose_name='Статус исполнения'),
        ),
    ]
