# Generated by Django 5.2 on 2025-04-20 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_from', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.group', verbose_name='Тип поручения'),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_users', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_executors',
            field=models.ManyToManyField(through='tasks.TaskUser', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AddConstraint(
            model_name='taskuser',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_for_user'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title', 'assignment_date'), name='unique_task'),
        ),
    ]
