# Generated by Django 5.2 on 2025-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execution_status',
            field=models.CharField(choices=[('completed', 'исполнено'), ('on_execution', 'на исполнении'), ('overdue', 'просрочено')], default='on_execution', verbose_name='Статус исполнения'),
        ),
    ]
