# Generated by Django 5.2 on 2025-04-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='responsible_executors',
            new_name='executors',
        ),
    ]
