# Generated by Django 5.2 on 2025-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Номер поручения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='execution_status',
            field=models.CharField(choices=[('completed', 'исполнено'), ('on_execution', 'на исполнении'), ('urgent', 'urgent'), ('overdue', 'просрочено')], default='on_execution', verbose_name='Статус исполнения'),
        ),
    ]
