# Generated by Django 5.2 on 2025-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_responsible_executors_task_executors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execution_status',
            field=models.CharField(choices=[('исполнено', 'исполнено'), ('на исполнении', 'на исполнении')], default='на исполнении', verbose_name='Статус исполнения'),
        ),
    ]
