# Generated by Django 5.2 on 2025-04-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_responsible_executor_alter_task_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
    ]
