# Generated by Django 5.2 on 2025-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_execution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execution_status',
            field=models.CharField(choices=[('completed', 'исполнено'), ('on_execution', 'на исполнении')], default='on_execution', verbose_name='Статус исполнения'),
        ),
    ]
