# Generated by Django 5.2 on 2025-04-29 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_number_alter_task_execution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasks_file',
            field=models.FileField(blank=True, help_text='Разрешенные расширения: doc, docx, pdf.', null=True, upload_to='uploaded/access_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Локальное НПА'),
        ),
    ]
