# Generated by Django 5.2 on 2025-04-29 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_tasks_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['execution_date'], 'verbose_name': 'Поручение', 'verbose_name_plural': 'Поручения'},
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redirected_tasks', to='tasks.task', verbose_name='Перенаправлено от'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasks_file',
            field=models.FileField(blank=True, help_text='Разрешенные расширения: doc, docx, pdf, jpg, jpeg, png.', null=True, upload_to='uploaded/tasks_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Приложение'),
        ),
    ]
