# Generated by Django 5.2 on 2025-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_options_task_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='execution_status',
            field=models.CharField(choices=[('completed', 'исполнено'), ('on_execution', 'на исполнении'), ('urgent', 'срочное'), ('overdue', 'просрочено')], default='on_execution', verbose_name='Статус исполнения'),
        ),
    ]
