# Generated by Django 5.2 on 2025-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_unique_task_task_unique_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='execution_status',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Статус исполнения'),
        ),
    ]
