# Generated by Django 5.2 on 2025-07-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_unique_task_task_unique_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redirected_tasks', to='tasks.task', verbose_name='Родительское поручение'),
        ),
    ]
