# Generated by Django 5.2 on 2025-09-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_group_options_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Статус исполнения'),
        ),
    ]
