# Generated by Django 5.2 on 2025-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='resolution',
            field=models.TextField(default=1, max_length=10000, verbose_name='Резолюция'),
            preserve_default=False,
        ),
    ]
