# Generated by Django 5.2 on 2025-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_task_description_task_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed_by_author',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отметка об исполнении инициатором'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed_by_executor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отметка об исполнении исполнителем'),
        ),
    ]
