# Generated by Django 5.2 on 2025-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_task_is_completed_task_is_completed_by_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed_by_author',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отметка об исполнении поручения инициатором'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed_by_executor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отметка об исполнении поручения исполнителем'),
        ),
    ]
