# Generated by Django 5.2 on 2025-09-11 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_is_completed_by_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='application',
            field=models.FileField(blank=True, help_text='Разрешенные расширения: doc, docx, pdf, jpg, jpeg, png.', null=True, upload_to='uploaded/applications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Приложение к исполнению'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasks_file',
            field=models.FileField(blank=True, help_text='Разрешенные расширения: doc, docx, pdf, jpg, jpeg, png.', null=True, upload_to='uploaded/tasks_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Приложение к поручению'),
        ),
    ]
