# Generated by Django 5.2 on 2025-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_task_application_alter_task_tasks_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executions_comment',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Комментарий к исполнению'),
        ),
    ]
