# Generated by Django 5.2 on 2025-09-13 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_executions_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(related_name='execution_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
    ]
