# Generated by Django 5.2 on 2025-09-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed_by_author',
            new_name='is_closed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_completed_by_executor',
            new_name='is_completed',
        ),
    ]
