# Generated by Django 5.2 on 2025-09-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_rename_is_completed_by_author_task_is_closed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='application',
            new_name='executions_application',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasks_file',
            new_name='tasks_application',
        ),
    ]
