# Generated by Django 5.2 on 2025-09-26 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_rename_application_task_executions_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='initiator',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title', 'number', 'initiator', 'assignment_date'), name='unique_task'),
        ),
    ]
