# Generated by Django 5.2 on 2025-09-26 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_remove_task_unique_task_rename_author_task_initiator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
    ]
