# Generated by Django 5.2 on 2025-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_task_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование типа поручения'),
        ),
    ]
