# Generated by Django 5.2 on 2025-04-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Заместитель директора', 'Заместитель директора'), ('Начальник отдела', 'Начальник отдела'), ('Сотрудник отдела', 'Сотрудник отдела'), ('Администратор', 'Администратор')], default='Сотрудник отдела', max_length=64, verbose_name='Статус'),
        ),
    ]
