# Generated by Django 5.2 on 2025-04-29 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_departments', to=settings.AUTH_USER_MODEL, verbose_name='Курирующий заместитель'),
        ),
    ]
