# Generated by Django 5.2 on 2025-04-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_department_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Заместитель директора', 'Заместитель директора'), ('Начальник отдела', 'Начальник отдела'), ('Заместитель начальника отдела', 'Заместитель начальника отдела'), ('Сотрудник отдела', 'Сотрудник отдела'), ('Администратор', 'Администратор')], default='Сотрудник отдела', max_length=64, verbose_name='Статус'),
        ),
    ]
