# Generated by Django 5.2 on 2025-09-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='department',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_departments', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
    ]
