# Generated by Django 5.2 on 2025-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Директор', 'Директор'), ('Заместитель директора', 'Заместитель директора'), ('Начальник отдела', 'Начальник отдела'), ('Заместитель начальника отдела', 'Заместитель начальника отдела'), ('Сотрудник отдела', 'Сотрудник отдела'), ('Администратор', 'Администратор')], default='Сотрудник отдела', verbose_name='Должность')),
            ],
        ),
    ]
