# Generated by Django 5.2 on 2025-12-02 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_departments', to='departments.employee', verbose_name='Куратор'),
        ),
    ]
